apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-flux
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/bl-robinson/home-flux.git
  secretRef:
    name: git-token
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-flux
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: home-flux
  path: "./clusters/home/"
  prune: true
  timeout: 1m
